import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import LeftSidebar from "./components/LeftSidebar"; // ✅ Import your sidebar

// ✅ Load Montserrat from Google Fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-sans antialiased bg-black text-white`}
      >
        <div className="flex flex-row w-full h-screen">
          {/* Sidebar stays across all pages */}
          <LeftSidebar />

          {/* Main content area */}
          <main className="flex-1 ml-[16.4%] bg-black overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
